"""initial migration

Revision ID: cec96e67f2f3
Revises: 
Create Date: 2026-07-03 10:00:26.512555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cec96e67f2f3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_table')
    op.drop_table('file_table')
    op.drop_table('complaints_table')
    op.drop_table('skill_sets_table')
    op.drop_table('job_postings_table')
    op.drop_table('notification_table')
    op.drop_table('payments_table')
    op.drop_table('chats_table')
    op.drop_table('connects_tables')
    op.drop_table('connects_management')
    op.drop_table('ratings_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ratings_table',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_rated_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], name=op.f('ratings_table_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ratings_table_pkey'))
    )
    op.create_table('connects_management',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('connects', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('connects_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], name=op.f('connects_management_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('connects_management_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('connects_management_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('connects_tables',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('available_connects', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], name=op.f('connects_tables_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('connects_tables_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('connects_tables_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('chats_table',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('room', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('chat_cleared_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('receiver_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_seen', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['user_table.id'], name=op.f('chats_table_sender_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('chats_table_pkey'))
    )
    op.create_table('payments_table',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('is_received', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('payment_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('business_short_code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mpesa_receipt_number', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('result_code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('transaction_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], name=op.f('payments_table_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('payments_table_pkey'))
    )
    op.create_table('notification_table',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('msg', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('link', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('unread', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('important', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], name=op.f('notification_table_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('notification_table_pkey'))
    )
    op.create_table('job_postings_table',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('job_description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('job_category', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], name=op.f('job_postings_table_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('job_postings_table_pkey'))
    )
    op.create_table('skill_sets_table',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('skill_set', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], name=op.f('skill_sets_table_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('skill_sets_table_pkey'))
    )
    op.create_table('complaints_table',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('complaint_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('complaint_info', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], name=op.f('complaints_table_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('complaints_table_pkey'))
    )
    op.create_table('file_table',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_profile', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('file_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], name=op.f('file_table_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('file_table_pkey'))
    )
    op.create_table('user_table',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('time_zone', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('account_status', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('account_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('account_class', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('failed_login_attempts', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('account_created_datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('account_locked_datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('account_locked', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_account_scheduled_for_deletion', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('account_scheduled_for_deletion_datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('user_table_pkey'))
    )
    # ### end Alembic commands ###
